name: Terraform - 3
on:
  push:
    branches:
      - master
    
jobs:
  Validate:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init and validate
      run: |
        echo `pwd`
        echo "** Running Terraform Init**"
        terraform init
        
        echo "** Running Terraform Validate**"
        terraform validate
      
      working-directory: ${{ github.event.inputs.tfpath }}
